### ISSUE TITLE
Get up front trajectories in simulation

### ISSUE THREAD

**Issue by Vuwij** [utra-robosoccer/soccer_ws#113]
soccer_trajectories/test/test_getupfront.test

**Comment by lkunelk** [comment]
You should try increasing the collision box on feet, since we are increasing the physical foot anyways

**Comment by Vuwij** [comment]
@lkunelk sure but Lukasz need to know the dimensions of the new foot @LiinaSadul can you provide him the dimensions

**Comment by LiinaSadul** [comment]
![image](https://user-images.githubusercontent.com/60044740/74199308-cb87bb00-4c31-11ea-9ab9-40e1f44672ef.png)

@ljagodz  The new foot is 100mm x 120mm
