### ISSUE TITLE
Pick Microcontroller for Foot Pressure Sensors

### ISSUE THREAD

**Issue by lkunelk** [utra-robosoccer/soccer_ws#82]

**Comment by cdalizadeh** [comment]
The STM32L432 microcontroller is suitable for the task. It has a 12-bit, 10-channel ADC, and I2C capabilities.

**Comment by JeffZZM** [comment]
https://www.digikey.com/products/en?WT.z_cid=sp_497_0928_buynow&Enterprise=44&lang=en&Vendor=497&mpart=STM32L412KBT6
